M48
; DRILL file {KiCad 9.0.4} date 2025-10-14T22:23:38+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-10-14T22:23:38+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1378
%
G90
G05
T1
X1.2488Y-3.7076
X1.2488Y-3.9352
T2
X4.325Y-4.1837
M30
